apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: semaphore
  name: python-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-project
  template:
    metadata:
      labels:
        app: python-project
    spec:
      containers:
        - name: front-end
          image: bharathsharath/python-project
          imagePullPolicy: Always
          ports:
            - containerPort: 8732
          resources:
            limits:
             cpu: 500m
            requests:
             cpu: 200m
