apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    app: python-service
spec:
  selector:
    app: python-project
  ports:
  - port: 8555
    targetPort: 8732
    nodePort: 31000
  type: NodePort
